version: '3.8'
services:
  mlflow:
    build:
      context: ./mlflow
    image: mlflow-dev
    container_name: mlflow-server
    ports:
      - "5001:5000"
    volumes:
      - /tmp/mlflow/mlartifacts:/mlflow/mlartifacts
      - /tmp/mlflow/runs:/mlflow/mlruns
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 512m
  prefect:
    build:
      context: ./prefect
    image: prefect-dev
    container_name: prefect-server
    ports:
      - "4200:4200"
    volumes:
      - /tmp/prefect:/root/.prefect
