services:
  mlflow:
    build:
      context: ./mlflow
    image: mlflow-dev
    container_name: mlflow-server
    network_mode: host  # Use host network
    volumes:
      - /tmp/mlflow/mlartifacts:/mlflow/mlartifacts
      - /tmp/mlflow/runs:/mlflow/mlruns
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 512m
  prefect:
    build:
      context: ./prefect
    image: prefect-dev
    container_name: prefect-server
    network_mode: host  # Use host network
    volumes:
      - /tmp/prefect:/root/.prefect
  evidently:
    build:
      context: ./evidently
    image: evidently-dev
    container_name: evidently-server
    network_mode: host  # Use host network
    volumes:
      - /tmp/evidently/workspace:/app/workspace
