version: '3.8'
services:
  mlflow:
    build:
      context: ./mlflow
    image: mlflow-dev
    container_name: mlflow-server
    ports:
      - "5001:5000"
    volumes:
      - /tmp/mlflow-server/mlruns:/mlflow/mlruns
      - /tmp/mlflow-server/mlartifacts:/mlflow/mlartifacts
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 512m
  prefect:
    build:
      context: ./prefect
    image: prefect-dev
    container_name: prefect-server
    ports:
      - "4200:4200"
  mage:
    build: 
      context: ./mage
    image: mage-dev
    container_name: mage-server
    ports:
      - "6789:6789"
    volumes:
      - /Users/sha/ws/code/mlops-zoomcamp-1/03-orchestration:/home/src
    deploy:
      resources:
        limits:
          memory: 10g
        reservations:
          memory: 1g